config/routes.rb
Rails.application.routes.draw do
  resources :documents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_many_attached :files
  validates :name, presence: true

end

app/models/user.rb
# frozen_string_literal: true

# app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  validates :name, presence: true
  validates :avatar, attached: true,
                     content_type: %w[image/png image/jpg image/jpeg],
                     size: { less_than: 3.megabytes, message: 'is not given between size' },
                     dimension: { width: { min: 100, max: 2400 },
                                  height: { min: 100, max: 1800 }, message: 'is not given between dimension' }

  before_validation :set_avatar_filename


  private

  # Set custom filename
  def set_avatar_filename
    avatar.blob.update(filename: secure_filename) if avatar.attached? && avatar.new_record?
  end


  protected

  def secure_filename
    var = :"@avatar_secure_token"
    token = instance_variable_get(var) || instance_variable_set(var, SecureRandom.uuid)
    "#{token}-#{Time.now.strftime('%d%m%Y%H%M%S%L-%12N')}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show; end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit; end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def document_params
    params.require(:document).permit(:name, files: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :age, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :files %>
    <%= form.file_field :files, multiple: true %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>


<% if @document.files.attached? %>
  <div>
    <strong>Files:</strong>
    <% @document.files.each do |file| %>
      <p>
        <!-- previewable?:  Returns true if any registered previewer accepts the blob. By default, this will return true for videos and PDF documents -->
        <% if file.previewable? %>
          Thumb (<%= file.filename %>): <%= link_to image_tag(file.preview(resize: '200X200')),  file , target: '_blank' %> | &nbsp;
          <% if file.video? %>
            play Video:<%= video_tag rails_blob_path(file), controls: true, width: 400, height: 400 %>
          <% else  %>
            download :<%= link_to  "Download", rails_blob_path(file, disposition: 'attachment')%>
          <% end  %>
        <% elsif file.variable? %>
          <%= link_to image_tag(file.variant(resize: '100X100')), file , target: '_blank' %>
        <% elsif file.audio? %>
          play audio(<%= file.filename %>): <%= audio_tag(rails_blob_path(file), autoplay: false, controls: true) %>
        <% else %>
          <%= link_to  "Download file (#{file.filename})", rails_blob_path(file, disposition: 'attachment')%>
        <% end %>
    <% end %>
    </p>
  </div>
<% end %>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5ActiveStorage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div style="align-content: center">
    <%= link_to 'Users', users_path %> &nbsp; <%= link_to 'Documents', documents_path %>
  </div>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>
<% if @user.avatar.attached? %>
  <p>
    <b> Original:</b> <br/>
    <%= image_tag url_for(@user.avatar) %>
  </p>
  <p>
    <b> Thumb: </b><br/>
    <%= image_tag url_for(@user.avatar.variant(resize: '100x100')) %>
  </p>
  <p>
    <b> Download: </b><br/>
    <%= link_to "#{@user.avatar.filename} (download)", rails_blob_path(@user.avatar, disposition: "attachment") %>
  </p>
<% end %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>